name: speed
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.40
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - gcc=12.2.0
  - gcc_impl_linux-64=12.2.0
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libsanitizer=12.2.0
  - libstdcxx-ng=12.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.11.3
  - readline=8.2
  - setuptools=66.0.0
  - sqlite=3.41.2
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - ase==3.22.1
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - cachetools==5.3.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - emmet-core==0.55.2
      - filelock==3.9.0
      - flatbuffers==23.5.9
      - fonttools==4.39.4
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - future==0.18.3
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.18.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5py==3.8.0
      - hydra-core==1.3.2
      - idna==3.4
      - jax==0.4.10
      - jinja2==3.1.2
      - joblib==1.2.0
      - keras==2.12.0
      - kiwisolver==1.4.4
      - latexcodec==2.0.1
      - libclang==16.0.0
      - lightning-utilities==0.8.0
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - ml-dtypes==0.1.0
      - monty==2023.5.8
      - mp-api==0.33.3
      - mpmath==1.2.1
      - msgpack==1.0.5
      - multidict==6.0.4
      - multiprocess==0.70.14
      - networkx==3.0
      - numpy==1.23.5
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - p-tqdm==1.4.0
      - packaging==23.1
      - palettable==3.3.3
      - pandas==2.0.1
      - pathos==0.3.0
      - pathtools==0.1.2
      - pillow==9.3.0
      - plotly==5.14.1
      - pox==0.3.2
      - ppft==1.7.6.6
      - protobuf==4.23.1
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybtex==0.24.0
      - pydantic==1.10.7
      - pymatgen==2023.5.10
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - pytorch-lightning==2.0.2
      - pytz==2023.3
      - pyyaml==6.0
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - ruamel-yaml==0.17.26
      - ruamel-yaml-clib==0.2.7
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.23.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smact==2.5.1
      - smmap==5.0.0
      - spglib==2.0.2
      - sympy==1.11.1
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - torch==2.0.1+cpu
      - torch-geometric==2.3.1
      - torchaudio==2.0.2+cpu
      - torchmetrics==0.11.4
      - torchvision==0.15.2+cpu
      - tqdm==4.65.0
      - typing-extensions==4.4.0
      - tzdata==2023.3
      - uncertainties==3.1.7
      - urllib3==1.26.13
      - wandb==0.15.3
      - werkzeug==2.3.4
      - wrapt==1.14.1
      - yarl==1.9.2
